# env_files = ["../nb_secrets.env"]

[tasks.update-surreal]
command = "update-surreal"

[tasks.start-db]
command = "surreal"
args = [
    "start",
    "--log",
    "debug",
    "--bind",
    "127.0.0.1:52000",
    "surrealkv://../../dbs/novabyte.blog.db",
]

[tasks.init-db]
command = "surreal"
args = [
    "start",
    "--log",
    "debug",
    "--user",
    "root",
    "--pass",
    "root",
    "--bind",
    "127.0.0.1:52000",
    "surrealkv://../../dbs/novabyte.blog.db",
]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.release]
command = "cargo"
args = ["build", "--release"]

[tasks.run]
command = "cargo"
args = [
    "run"
]

[tasks.refresh]
dependencies = ["format", "run"]

[tasks.init-then-start]
dependencies = ["init-db", "start-db"]
