#!/bin/bash

source ../nb_secrets.env
cd "$(dirname "$0")"
DB_NAME=$DB_NAME DB_NAMESPACE=$DB_NAMESPACE DB_PASSWORD=$DB_PASSWORD DB_USER=$DB_USER DB_ADDRESS=$DB_ADDRESS SERVER_ADDRESS=$SERVER_ADDRESS RUST_LOG=$RUST_LOG REFRESH_DURATION_DAYS=$REFRESH_DURATION_DAYS JWT_DURATION_MINUTES=$JWT_DURATION_MINUTES NOVA_SECRET=$NOVA_SECRET ALLOWED_ORIGINS=$ALLOWED_ORIGINS ./nb_blog_api